# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.srcs/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/FullGameSchema_LocationFSM_wrapper_0_0.xci
# IP: The module: 'FullGameSchema_LocationFSM_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location0_0_0/LocationFSM_Location0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location0_0_0 || ORIG_REF_NAME==LocationFSM_Location0_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location1_0_0/LocationFSM_Location1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location1_0_0 || ORIG_REF_NAME==LocationFSM_Location1_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location2_0_0/LocationFSM_Location2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location2_0_0 || ORIG_REF_NAME==LocationFSM_Location2_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location3_0_0/LocationFSM_Location3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location3_0_0 || ORIG_REF_NAME==LocationFSM_Location3_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location4_0_0/LocationFSM_Location4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location4_0_0 || ORIG_REF_NAME==LocationFSM_Location4_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location5_0_0/LocationFSM_Location5_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location5_0_0 || ORIG_REF_NAME==LocationFSM_Location5_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location6_0_0/LocationFSM_Location6_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location6_0_0 || ORIG_REF_NAME==LocationFSM_Location6_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_0/LocationFSM_xup_dff_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_0 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_1/LocationFSM_xup_dff_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_1 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_1} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_2/LocationFSM_xup_dff_reset_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_2 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_2} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_3/LocationFSM_xup_dff_reset_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_3 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_3} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_4/LocationFSM_xup_dff_reset_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_4 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_4} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_5/LocationFSM_xup_dff_reset_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_5 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_5} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_set_0_0/LocationFSM_xup_dff_set_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_set_0_0 || ORIG_REF_NAME==LocationFSM_xup_dff_set_0_0} -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location0_0_0/src/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location0_0_0 || ORIG_REF_NAME==LocationFSM_Location0_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location1_0_0/src/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location1_0_0 || ORIG_REF_NAME==LocationFSM_Location1_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location2_0_0/src/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location2_0_0 || ORIG_REF_NAME==LocationFSM_Location2_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location3_0_0/src/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location3_0_0 || ORIG_REF_NAME==LocationFSM_Location3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location4_0_0/src/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location4_0_0 || ORIG_REF_NAME==LocationFSM_Location4_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location5_0_0/src/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location5_0_0 || ORIG_REF_NAME==LocationFSM_Location5_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location6_0_0/src/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location6_0_0 || ORIG_REF_NAME==LocationFSM_Location6_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/Nexys-A7-100T-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullGameSchema_LocationFSM_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_ooc.xdc

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.srcs/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/FullGameSchema_LocationFSM_wrapper_0_0.xci
# IP: The module: 'FullGameSchema_LocationFSM_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location0_0_0/LocationFSM_Location0_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location0_0_0 || ORIG_REF_NAME==LocationFSM_Location0_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location1_0_0/LocationFSM_Location1_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location1_0_0 || ORIG_REF_NAME==LocationFSM_Location1_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location2_0_0/LocationFSM_Location2_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location2_0_0 || ORIG_REF_NAME==LocationFSM_Location2_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location3_0_0/LocationFSM_Location3_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location3_0_0 || ORIG_REF_NAME==LocationFSM_Location3_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location4_0_0/LocationFSM_Location4_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location4_0_0 || ORIG_REF_NAME==LocationFSM_Location4_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location5_0_0/LocationFSM_Location5_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location5_0_0 || ORIG_REF_NAME==LocationFSM_Location5_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location6_0_0/LocationFSM_Location6_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_Location6_0_0 || ORIG_REF_NAME==LocationFSM_Location6_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_0/LocationFSM_xup_dff_reset_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_0 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_1/LocationFSM_xup_dff_reset_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_1 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_1} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_2/LocationFSM_xup_dff_reset_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_2 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_2} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_3/LocationFSM_xup_dff_reset_0_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_3 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_3} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_4/LocationFSM_xup_dff_reset_0_4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_4 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_4} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_reset_0_5/LocationFSM_xup_dff_reset_0_5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_reset_0_5 || ORIG_REF_NAME==LocationFSM_xup_dff_reset_0_5} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_xup_dff_set_0_0/LocationFSM_xup_dff_set_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LocationFSM_xup_dff_set_0_0 || ORIG_REF_NAME==LocationFSM_xup_dff_set_0_0} -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location0_0_0/src/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location0_0_0 || ORIG_REF_NAME==LocationFSM_Location0_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location1_0_0/src/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location1_0_0 || ORIG_REF_NAME==LocationFSM_Location1_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location2_0_0/src/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location2_0_0 || ORIG_REF_NAME==LocationFSM_Location2_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location3_0_0/src/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location3_0_0 || ORIG_REF_NAME==LocationFSM_Location3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location4_0_0/src/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location4_0_0 || ORIG_REF_NAME==LocationFSM_Location4_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location5_0_0/src/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location5_0_0 || ORIG_REF_NAME==LocationFSM_Location5_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_Location6_0_0/src/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LocationFSM_Location6_0_0 || ORIG_REF_NAME==LocationFSM_Location6_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/Nexys-A7-100T-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullGameSchema_LocationFSM_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/src/LocationFSM_ooc.xdc
