# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.srcs/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/FullGameSchema_SwordFSM_wrapper_0_0.xci
# IP: The module: 'FullGameSchema_SwordFSM_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/src/SwordFSM_Sword_0_0/SwordFSM_Sword_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SwordFSM_Sword_0_0 || ORIG_REF_NAME==SwordFSM_Sword_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/src/SwordFSM_xup_dff_reset_0_0/SwordFSM_xup_dff_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SwordFSM_xup_dff_reset_0_0 || ORIG_REF_NAME==SwordFSM_xup_dff_reset_0_0} -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/src/SwordFSM_Sword_0_0/src/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SwordFSM_Sword_0_0 || ORIG_REF_NAME==SwordFSM_Sword_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/src/Nexys-A7-100T-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullGameSchema_SwordFSM_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/src/SwordFSM_ooc.xdc

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.srcs/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/FullGameSchema_SwordFSM_wrapper_0_0.xci
# IP: The module: 'FullGameSchema_SwordFSM_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/src/SwordFSM_Sword_0_0/SwordFSM_Sword_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SwordFSM_Sword_0_0 || ORIG_REF_NAME==SwordFSM_Sword_0_0} -quiet] -quiet

# IP: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/src/SwordFSM_xup_dff_reset_0_0/SwordFSM_xup_dff_reset_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SwordFSM_xup_dff_reset_0_0 || ORIG_REF_NAME==SwordFSM_xup_dff_reset_0_0} -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/src/SwordFSM_Sword_0_0/src/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SwordFSM_Sword_0_0 || ORIG_REF_NAME==SwordFSM_Sword_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/src/Nexys-A7-100T-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullGameSchema_SwordFSM_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/src/SwordFSM_ooc.xdc
