# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/Nexys-A7-100T-Master.xdc

# Block Designs: bd/FullGameSchema/FullGameSchema.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullGameSchema || ORIG_REF_NAME==FullGameSchema} -quiet] -quiet

# IP: bd/FullGameSchema/ip/FullGameSchema_Edge_Detector_0_0/FullGameSchema_Edge_Detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullGameSchema_Edge_Detector_0_0 || ORIG_REF_NAME==FullGameSchema_Edge_Detector_0_0} -quiet] -quiet

# IP: bd/FullGameSchema/ip/FullGameSchema_Edge_Detector_0_1/FullGameSchema_Edge_Detector_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullGameSchema_Edge_Detector_0_1 || ORIG_REF_NAME==FullGameSchema_Edge_Detector_0_1} -quiet] -quiet

# IP: bd/FullGameSchema/ip/FullGameSchema_Edge_Detector_0_2/FullGameSchema_Edge_Detector_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullGameSchema_Edge_Detector_0_2 || ORIG_REF_NAME==FullGameSchema_Edge_Detector_0_2} -quiet] -quiet

# IP: bd/FullGameSchema/ip/FullGameSchema_Edge_Detector_0_3/FullGameSchema_Edge_Detector_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullGameSchema_Edge_Detector_0_3 || ORIG_REF_NAME==FullGameSchema_Edge_Detector_0_3} -quiet] -quiet

# IP: bd/FullGameSchema/ip/FullGameSchema_SwordFSM_wrapper_0_0/FullGameSchema_SwordFSM_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullGameSchema_SwordFSM_wrapper_0_0 || ORIG_REF_NAME==FullGameSchema_SwordFSM_wrapper_0_0} -quiet] -quiet

# IP: bd/FullGameSchema/ip/FullGameSchema_LocationFSM_wrapper_0_0/FullGameSchema_LocationFSM_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullGameSchema_LocationFSM_wrapper_0_0 || ORIG_REF_NAME==FullGameSchema_LocationFSM_wrapper_0_0} -quiet] -quiet

# XDC: c:/Users/ashin/OneDrive/Desktop/Lab3_SwordFSM/lab3/lab3.gen/sources_1/bd/FullGameSchema/FullGameSchema_ooc.xdc
